/*
 Navicat Premium Dump SQL

 Source Server         : db_wa_helpdesk
 Source Server Type    : PostgreSQL
 Source Server Version : 160014 (160014)
 Source Host           : 10.100.1.220:5432
 Source Catalog        : db_aplikasi
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160014 (160014)
 File Encoding         : 65001

 Date: 09/09/2026 11:51:09
*/


-- ----------------------------
-- Sequence structure for divisi_kd_divisi_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."divisi_kd_divisi_seq";
CREATE SEQUENCE "public"."divisi_kd_divisi_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for keyword_divisi_kd_keyword_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."keyword_divisi_kd_keyword_seq";
CREATE SEQUENCE "public"."keyword_divisi_kd_keyword_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for kirim_wa_id_kirim_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."kirim_wa_id_kirim_seq";
CREATE SEQUENCE "public"."kirim_wa_id_kirim_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for pengguna_kd_user_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."pengguna_kd_user_seq";
CREATE SEQUENCE "public"."pengguna_kd_user_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for pengguna_kd_user_seq1
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."pengguna_kd_user_seq1";
CREATE SEQUENCE "public"."pengguna_kd_user_seq1" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for pesan_masuk_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."pesan_masuk_id_seq";
CREATE SEQUENCE "public"."pesan_masuk_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for divisi
-- ----------------------------
DROP TABLE IF EXISTS "public"."divisi";
CREATE TABLE "public"."divisi" (
  "kd_divisi" int4 NOT NULL DEFAULT nextval('divisi_kd_divisi_seq'::regclass),
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "description" text COLLATE "pg_catalog"."default",
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for keyword_divisi
-- ----------------------------
DROP TABLE IF EXISTS "public"."keyword_divisi";
CREATE TABLE "public"."keyword_divisi" (
  "kd_keyword" int4 NOT NULL DEFAULT nextval('keyword_divisi_kd_keyword_seq'::regclass),
  "kd_divisi" int4,
  "keyword" varchar(255) COLLATE "pg_catalog"."default",
  "kd_mapping_divisi" int4
)
;

-- ----------------------------
-- Table structure for keyword_unit
-- ----------------------------
DROP TABLE IF EXISTS "public"."keyword_unit";
CREATE TABLE "public"."keyword_unit" (
  "kd_keyword" int4,
  "kd_unit" int4,
  "keyword" varchar(255) COLLATE "pg_catalog"."default",
  "status_aktif" int2
)
;

-- ----------------------------
-- Table structure for kirim_wa
-- ----------------------------
DROP TABLE IF EXISTS "public"."kirim_wa";
CREATE TABLE "public"."kirim_wa" (
  "id_kirim" int4 NOT NULL DEFAULT nextval('kirim_wa_id_kirim_seq'::regclass),
  "nomor_pengirim" varchar(30) COLLATE "pg_catalog"."default" NOT NULL,
  "isi_pesan" text COLLATE "pg_catalog"."default" NOT NULL,
  "tg_kirim" timestamp(6) DEFAULT LOCALTIMESTAMP(0),
  "status_kirim" int4 DEFAULT 0,
  "kd_user" int4,
  "id_pesan_masuk" int4,
  "solusi" varchar(255) COLLATE "pg_catalog"."default",
  "retry_count" int2 DEFAULT 0
)
;

-- ----------------------------
-- Table structure for mapping_divisi
-- ----------------------------
DROP TABLE IF EXISTS "public"."mapping_divisi";
CREATE TABLE "public"."mapping_divisi" (
  "kd_mapping_divisi" int4 NOT NULL,
  "nama_mapping" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for pengguna
-- ----------------------------
DROP TABLE IF EXISTS "public"."pengguna";
CREATE TABLE "public"."pengguna" (
  "kd_user" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "nama_user" varchar(255) COLLATE "pg_catalog"."default",
  "nomor_hp" varchar(255) COLLATE "pg_catalog"."default",
  "kd_unit" int4,
  "whatsapp_lid" varchar COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for pesan_masuk
-- ----------------------------
DROP TABLE IF EXISTS "public"."pesan_masuk";
CREATE TABLE "public"."pesan_masuk" (
  "id" int4 NOT NULL DEFAULT nextval('pesan_masuk_id_seq'::regclass),
  "whatsapp_id" varchar(255) COLLATE "pg_catalog"."default",
  "pengirim" varchar(255) COLLATE "pg_catalog"."default",
  "isi_pesan" text COLLATE "pg_catalog"."default",
  "tgl_lapor" timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  "nomor_pengirim" varchar(50) COLLATE "pg_catalog"."default",
  "status_selesai" int4 DEFAULT 0,
  "kd_divisi" int4,
  "tgl_proses" timestamp(6),
  "tgl_selesai" timestamp(6),
  "attachments" text[] COLLATE "pg_catalog"."default" DEFAULT '{}'::text[],
  "kd_unit_pelapor" int4,
  "chat_id" varchar COLLATE "pg_catalog"."default",
  "kd_user_proses" int4,
  "kd_user_done" int4 DEFAULT 0,
  "kd_user_up" int4,
  "tgl_up" timestamp(6),
  "status_hapus" int2,
  "attachments_done" text COLLATE "pg_catalog"."default",
  "kd_mapping_divisi" int4
)
;

-- ----------------------------
-- Table structure for unit
-- ----------------------------
DROP TABLE IF EXISTS "public"."unit";
CREATE TABLE "public"."unit" (
  "kd_unit" int4 NOT NULL,
  "nama_unit" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."divisi_kd_divisi_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."keyword_divisi_kd_keyword_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."kirim_wa_id_kirim_seq"
OWNED BY "public"."kirim_wa"."id_kirim";
SELECT setval('"public"."kirim_wa_id_kirim_seq"', 615, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."pengguna_kd_user_seq"
OWNED BY "public"."pengguna"."kd_user";
SELECT setval('"public"."pengguna_kd_user_seq"', 13, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."pengguna_kd_user_seq1"
OWNED BY "public"."pengguna"."kd_user";
SELECT setval('"public"."pengguna_kd_user_seq1"', 176, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."pesan_masuk_id_seq"
OWNED BY "public"."pesan_masuk"."id";
SELECT setval('"public"."pesan_masuk_id_seq"', 888, true);

-- ----------------------------
-- Primary Key structure for table divisi
-- ----------------------------
ALTER TABLE "public"."divisi" ADD CONSTRAINT "divisi_pkey" PRIMARY KEY ("kd_divisi");

-- ----------------------------
-- Primary Key structure for table keyword_divisi
-- ----------------------------
ALTER TABLE "public"."keyword_divisi" ADD CONSTRAINT "keyword_divisi_pkey" PRIMARY KEY ("kd_keyword");

-- ----------------------------
-- Indexes structure for table kirim_wa
-- ----------------------------
CREATE INDEX "idx_kirim_wa_status" ON "public"."kirim_wa" USING btree (
  "status_kirim" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table kirim_wa
-- ----------------------------
ALTER TABLE "public"."kirim_wa" ADD CONSTRAINT "kirim_wa_pkey" PRIMARY KEY ("id_kirim");

-- ----------------------------
-- Primary Key structure for table mapping_divisi
-- ----------------------------
ALTER TABLE "public"."mapping_divisi" ADD CONSTRAINT "mapping_divisi_pkey" PRIMARY KEY ("kd_mapping_divisi");

-- ----------------------------
-- Indexes structure for table pengguna
-- ----------------------------
CREATE INDEX "idx_pengguna_lid" ON "public"."pengguna" USING btree (
  "whatsapp_lid" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "pengguna_whatsapp_lid_key" ON "public"."pengguna" USING btree (
  "whatsapp_lid" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE whatsapp_lid IS NOT NULL;

-- ----------------------------
-- Uniques structure for table pengguna
-- ----------------------------
ALTER TABLE "public"."pengguna" ADD CONSTRAINT "pengguna_nomor_hp_unique" UNIQUE ("nomor_hp");

-- ----------------------------
-- Primary Key structure for table pengguna
-- ----------------------------
ALTER TABLE "public"."pengguna" ADD CONSTRAINT "user_pkey" PRIMARY KEY ("kd_user");

-- ----------------------------
-- Uniques structure for table pesan_masuk
-- ----------------------------
ALTER TABLE "public"."pesan_masuk" ADD CONSTRAINT "pesan_masuk_whatsapp_id_key" UNIQUE ("whatsapp_id");

-- ----------------------------
-- Primary Key structure for table pesan_masuk
-- ----------------------------
ALTER TABLE "public"."pesan_masuk" ADD CONSTRAINT "pesan_masuk_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table unit
-- ----------------------------
ALTER TABLE "public"."unit" ADD CONSTRAINT "unit_pkey" PRIMARY KEY ("kd_unit");

-- ----------------------------
-- Foreign Keys structure for table keyword_divisi
-- ----------------------------
ALTER TABLE "public"."keyword_divisi" ADD CONSTRAINT "fk_divisi" FOREIGN KEY ("kd_divisi") REFERENCES "public"."divisi" ("kd_divisi") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "public"."keyword_divisi" ADD CONSTRAINT "fk_divisi_keyword" FOREIGN KEY ("kd_divisi") REFERENCES "public"."divisi" ("kd_divisi") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table kirim_wa
-- ----------------------------
ALTER TABLE "public"."kirim_wa" ADD CONSTRAINT "fk_pesan_masuk" FOREIGN KEY ("id_pesan_masuk") REFERENCES "public"."pesan_masuk" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table pengguna
-- ----------------------------
ALTER TABLE "public"."pengguna" ADD CONSTRAINT "fk_pengguna_unit" FOREIGN KEY ("kd_unit") REFERENCES "public"."unit" ("kd_unit") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table pesan_masuk
-- ----------------------------
ALTER TABLE "public"."pesan_masuk" ADD CONSTRAINT "fk_divisi" FOREIGN KEY ("kd_divisi") REFERENCES "public"."divisi" ("kd_divisi") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."pesan_masuk" ADD CONSTRAINT "fk_kd_unit_pelapor" FOREIGN KEY ("kd_unit_pelapor") REFERENCES "public"."unit" ("kd_unit") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "public"."pesan_masuk" ADD CONSTRAINT "fk_pesan_pengguna" FOREIGN KEY ("kd_user_proses") REFERENCES "public"."pengguna" ("kd_user") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "public"."pesan_masuk" ADD CONSTRAINT "fk_pesan_user" FOREIGN KEY ("kd_user_proses") REFERENCES "public"."pengguna" ("kd_user") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "public"."pesan_masuk" ADD CONSTRAINT "pesan_masuk_kd_mapping_divisi_fkey" FOREIGN KEY ("kd_mapping_divisi") REFERENCES "public"."mapping_divisi" ("kd_mapping_divisi") ON DELETE NO ACTION ON UPDATE NO ACTION;
